### ISSUE TITLE
[BUG] Cannot Estimate Gas When Setting `maxFeePerGas` and `maxPriorityFeePerGas` as 0

### ISSUE THREAD

**Issue by doublespending** [etherspot/skandha#64]
### Describe the bug

Return Error when calling `eth_estimateUserOperationGas ` with valid parameters [`maxFeePerGas = 0` and `maxPriorityFeePerGas = 0`].

I suppose that `divisor` will become 0 here: https://github.com/etherspot/skandha/blob/master/packages/executor/src/modules/eth.ts#L154-L157

Server Side:
```
[10:37:58.940] ERROR (80848): division-by-zero [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-division-by-zero ] (fault=“division-by-zero”, operation=“div”, code=NUMERIC_FAULT, version=bignumber/5.7.0)
    err: {
      “type”: “Error”,
      “message”: “division-by-zero [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-division-by-zero ] (fault=\“division-by-zero\“, operation=\“div\“, code=NUMERIC_FAULT, version=bignumber/5.7.0)“,
      “stack”:
          Error: division-by-zero [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-division-by-zero ] (fault=“division-by-zero”, operation=“div”, code=NUMERIC_FAULT, version=bignumber/5.7.0)
              at Logger.makeError (/Users/caiweizhe/Documents/fork-repo/skandha/node_modules/@ethersproject/logger/lib/index.js:238:21)
              at Logger.throwError (/Users/caiweizhe/Documents/fork-repo/skandha/node_modules/@ethersproject/logger/lib/index.js:247:20)
              at throwFault (/Users/caiweizhe/Documents/fork-repo/skandha/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
              at BigNumber.div (/Users/caiweizhe/Documents/fork-repo/skandha/node_modules/@ethersproject/bignumber/lib/bignumber.js:65:13)
              at Eth.estimateUserOperationGas (file:///Users/caiweizhe/Documents/fork-repo/skandha/packages/executor/lib/modules/eth.js:103:49)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async EthAPI.estimateUserOperationGas (file:///Users/caiweizhe/Documents/fork-repo/skandha/packages/api/lib/modules/eth.js:32:16)
              at async Object.<anonymous> (file:///Users/caiweizhe/Documents/fork-repo/skandha/packages/api/lib/app.js:118:34)
      “reason”: “division-by-zero”,
      “code”: “NUMERIC_FAULT”,
      “fault”: “division-by-zero”,
      “operation”: “div”
    }
[10:37:58.941] INFO (80848): RESPONSE ::
    reqId: “req-20"
    body: {
      “error”: “Unexpected behaviour”
    }

```

Client Side:
```
Error: bad response (status=500, headers={"vary":"Origin","access-control-allow-origin":"*","content-type":"application/json; charset=utf-8","content-length":"32","date":"Fri, 28 Jul 2023 02:37:58 GMT","connection":"close"}, body="{\"error\":\"Unexpected behaviour\"}", requestBody="{\"method\":\"eth_estimateUserOperationGas\",\"params\":[{\"sender\":\"0x8A0C6A5D9fa1aCD7c1a3Bb497c3E28C09040Ee59\",\"nonce\":\"0x0\",\"initCode\":\"0xd731d6e8e372d7edaa8ddcd1083357c66a3438485fbfb9cf000000000000000000000000c7cc285a947cf05061653f312e4b0022133e8786000000000000000000000000000000000000000000000000000425f980e3bdf5\",\"callData\":\"0x\",\"callGasLimit\":\"0x88b8\",\"verificationGasLimit\":\"0x9da155\",\"preVerificationGas\":\"0x0\",\"maxFeePerGas\":\"0x0\",\"maxPriorityFeePerGas\":\"0x0\",\"paymasterAndData\":\"0x\",\"signature\":\"0xacedeade60761d732314f3ddece87416e88474d0af21055ed557b5f9765a5ee3136c819c21c0f30b6c462610bdf8c5e6aed283a8ab664f94a3d812260bba994d1c\"},\"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789\"],\"id\":111,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://127.0.0.1:14337/rpc", code=SERVER_ERROR, version=web/5.7.1)
```

### Expected behavior

Success

### Operating system

macOS

### Skandha version or commit hash

b6e9c68198bfd8ef83090cb4479cdda272287af2

**Comment by marie-fourier** [comment]
Thanks for reporting! We'll fix it shorly

**Comment by ch4r10t33r** [comment]
@doublespending Thanks for reporting. Please can you confirm if the issue is resolved with our latest release.

**Comment by doublespending** [comment]
Thank you. I find that this issue has been resolved.
